In [1]:
#LOGISTIC
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import metrics

from IPython.display import display, HTML

dataset = pd.read_csv('data.csv')

#Redundant variables
del dataset["id"]
del dataset["age_days"]

'''dataset = dataset[dataset.height <= 200]
dataset = dataset[dataset.height >= 120]
dataset = dataset[dataset.weight <= 160]
dataset = dataset[dataset.ap_hi.between(0,500)]
dataset = dataset[dataset.ap_lo.between(0,2000)]'''
'''
del dataset["gender"]
del dataset["alco"]'''

#separating the x and y variables
display(HTML(dataset.head(10).to_html()))
X = dataset.iloc[:, :-1]
print(X)
y = dataset.iloc[:, -1]
print(y)

#spliting the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 1)

#scaling the data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)

#Building the model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 1)
classifier.fit(X_train, y_train)

#predicting the testing data
y_pred = classifier.predict(X_test)
print(y_pred)
print(y_test)
#print(np.concatenate((y_pred, y_test),1))

#creating confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test, y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))

        age_year  height  weight  ap_hi  ...  cholesterol  gluc  smoke  active
0      50.391781     168    62.0    110  ...            1     1      0       1
1      55.419178     156    85.0    140  ...            3     1      0       1
2      51.663014     165    64.0    130  ...            3     1      0       0
3      48.282192     169    82.0    150  ...            1     1      0       1
4      47.873973     156    56.0    100  ...            1     1      0       0
...          ...     ...     ...    ...  ...          ...   ...    ...     ...
69995  52.712329     168    76.0    120  ...            1     1      1       1
69996  61.920548     158   126.0    140  ...            2     2      0       1
69997  52.235616     183   105.0    180  ...            3     1      0       0
69998  61.454795     163    72.0    135  ...            1     2      0       0
69999  56.273973     170    72.0    120  ...            2     1      0       1

[69840 rows x 9 columns]
0        0
1        1
2        1
3        1
4        0
        ..
69995    0
69996    1
69997    1
69998    1
69999    0
Name: cardio, Length: 69840, dtype: int64
[0.30191717 0.17748901 0.18036496 0.17527184 0.09547998 0.04726998
 0.01176241 0.00511549 0.00532915]
[[-0.81962294  0.45143565 -1.13818438 ...  3.09820221 -0.31137621
   0.49383652]
 [ 0.02195862  0.1994169  -0.57339587 ... -0.3949922  -0.31137621
   0.49383652]
 [-0.50291611 -0.17861123 -0.14980448 ... -0.3949922  -0.31137621
   0.49383652]
 ...
 [ 0.77282109  0.82946379 -0.36160018 ... -0.3949922  -0.31137621
   0.49383652]
 [ 0.93481946 -0.43062998  0.76797685 ...  3.09820221 -0.31137621
   0.49383652]
 [-2.00423605 -1.31269562 -1.56177577 ... -0.3949922  -0.31137621
   0.49383652]]
[1 1 0 ... 0 1 1]
21227    0
48374    0
11114    1
23464    1
15107    0
        ..
33702    1
8679     0
33777    0
30646    0
63496    1
Name: cardio, Length: 20952, dtype: int64
[[8102 2380]
 [3366 7104]]
Accuracy: 0.725754104620084
Precision: 0.7490510333192746
Recall: 0.6785100286532951

In [2]:
#per label classification
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.71      0.77      0.74     10482
           1       0.75      0.68      0.71     10470

    accuracy                           0.73     20952
   macro avg       0.73      0.73      0.73     20952
weighted avg       0.73      0.73      0.73     20952